// NOTE this copy is not actually used copy it manually into formatgen.cpp

#ifndef TINYIMAGEFORMAT_DXGIFORMAT
#define TINYIMAGEFORMAT_DXGIFORMAT

typedef enum TinyImageFormat_DXGI_FORMAT {

	TIF_DXGI_FORMAT_UNKNOWN = 0,
	TIF_DXGI_FORMAT_R32G32B32A32_TYPELESS = 1,
	TIF_DXGI_FORMAT_R32G32B32A32_FLOAT = 2,
	TIF_DXGI_FORMAT_R32G32B32A32_UINT = 3,
	TIF_DXGI_FORMAT_R32G32B32A32_SINT = 4,
	TIF_DXGI_FORMAT_R32G32B32_TYPELESS = 5,
	TIF_DXGI_FORMAT_R32G32B32_FLOAT = 6,
	TIF_DXGI_FORMAT_R32G32B32_UINT = 7,
	TIF_DXGI_FORMAT_R32G32B32_SINT = 8,
	TIF_DXGI_FORMAT_R16G16B16A16_TYPELESS = 9,
	TIF_DXGI_FORMAT_R16G16B16A16_FLOAT  = 10,
	TIF_DXGI_FORMAT_R16G16B16A16_UNORM = 11,
	TIF_DXGI_FORMAT_R16G16B16A16_UINT = 12,
	TIF_DXGI_FORMAT_R16G16B16A16_SNORM = 13,
	TIF_DXGI_FORMAT_R16G16B16A16_SINT = 14,
	TIF_DXGI_FORMAT_R32G32_TYPELESS = 15,
	TIF_DXGI_FORMAT_R32G32_FLOAT = 16,
	TIF_DXGI_FORMAT_R32G32_UINT = 17,
	TIF_DXGI_FORMAT_R32G32_SINT = 18,
	TIF_DXGI_FORMAT_R32G8X24_TYPELESS = 19,
	TIF_DXGI_FORMAT_D32_FLOAT_S8X24_UINT = 20,
	TIF_DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS = 21,
	TIF_DXGI_FORMAT_X32_TYPELESS_G8X24_UINT = 22,
	TIF_DXGI_FORMAT_R10G10B10A2_TYPELESS = 23,
	TIF_DXGI_FORMAT_R10G10B10A2_UNORM = 24,
	TIF_DXGI_FORMAT_R10G10B10A2_UINT = 25,
	TIF_DXGI_FORMAT_R11G11B10_FLOAT = 26,
	TIF_DXGI_FORMAT_R8G8B8A8_TYPELESS = 27,
	TIF_DXGI_FORMAT_R8G8B8A8_UNORM = 28,
	TIF_DXGI_FORMAT_R8G8B8A8_UNORM_SRGB = 29,
	TIF_DXGI_FORMAT_R8G8B8A8_UINT = 30,
	TIF_DXGI_FORMAT_R8G8B8A8_SNORM = 31,
	TIF_DXGI_FORMAT_R8G8B8A8_SINT = 32,
	TIF_DXGI_FORMAT_R16G16_TYPELESS = 33,
	TIF_DXGI_FORMAT_R16G16_FLOAT = 34,
	TIF_DXGI_FORMAT_R16G16_UNORM = 35,
	TIF_DXGI_FORMAT_R16G16_UINT = 36,
	TIF_DXGI_FORMAT_R16G16_SNORM = 37,
	TIF_DXGI_FORMAT_R16G16_SINT = 38,
	TIF_DXGI_FORMAT_R32_TYPELESS = 39,
	TIF_DXGI_FORMAT_D32_FLOAT = 40,
	TIF_DXGI_FORMAT_R32_FLOAT = 41,
	TIF_DXGI_FORMAT_R32_UINT = 42,
	TIF_DXGI_FORMAT_R32_SINT = 43,
	TIF_DXGI_FORMAT_R24G8_TYPELESS = 44,
	TIF_DXGI_FORMAT_D24_UNORM_S8_UINT = 45,
	TIF_DXGI_FORMAT_R24_UNORM_X8_TYPELESS = 46,
	TIF_DXGI_FORMAT_X24_TYPELESS_G8_UINT = 47,
	TIF_DXGI_FORMAT_R8G8_TYPELESS = 48,
	TIF_DXGI_FORMAT_R8G8_UNORM = 49,
	TIF_DXGI_FORMAT_R8G8_UINT = 50,
	TIF_DXGI_FORMAT_R8G8_SNORM = 51,
	TIF_DXGI_FORMAT_R8G8_SINT = 52,
	TIF_DXGI_FORMAT_R16_TYPELESS = 53,
	TIF_DXGI_FORMAT_R16_FLOAT = 54,
	TIF_DXGI_FORMAT_D16_UNORM = 55,
	TIF_DXGI_FORMAT_R16_UNORM = 56,
	TIF_DXGI_FORMAT_R16_UINT = 57,
	TIF_DXGI_FORMAT_R16_SNORM = 58,
	TIF_DXGI_FORMAT_R16_SINT = 59,
	TIF_DXGI_FORMAT_R8_TYPELESS = 60,
	TIF_DXGI_FORMAT_R8_UNORM = 61,
	TIF_DXGI_FORMAT_R8_UINT = 62,
	TIF_DXGI_FORMAT_R8_SNORM = 63,
	TIF_DXGI_FORMAT_R8_SINT = 64,
	TIF_DXGI_FORMAT_A8_UNORM = 65,
	TIF_DXGI_FORMAT_R1_UNORM = 66,
	TIF_DXGI_FORMAT_R9G9B9E5_SHAREDEXP = 67,
	TIF_DXGI_FORMAT_R8G8_B8G8_UNORM = 68,
	TIF_DXGI_FORMAT_G8R8_G8B8_UNORM = 69,
	TIF_DXGI_FORMAT_BC1_TYPELESS = 70,
	TIF_DXGI_FORMAT_BC1_UNORM = 71,
	TIF_DXGI_FORMAT_BC1_UNORM_SRGB = 72,
	TIF_DXGI_FORMAT_BC2_TYPELESS = 73,
	TIF_DXGI_FORMAT_BC2_UNORM = 74,
	TIF_DXGI_FORMAT_BC2_UNORM_SRGB = 75,
	TIF_DXGI_FORMAT_BC3_TYPELESS = 76,
	TIF_DXGI_FORMAT_BC3_UNORM = 77,
	TIF_DXGI_FORMAT_BC3_UNORM_SRGB = 78,
	TIF_DXGI_FORMAT_BC4_TYPELESS = 79,
	TIF_DXGI_FORMAT_BC4_UNORM = 80,
	TIF_DXGI_FORMAT_BC4_SNORM = 81,
	TIF_DXGI_FORMAT_BC5_TYPELESS = 82,
	TIF_DXGI_FORMAT_BC5_UNORM = 83,
	TIF_DXGI_FORMAT_BC5_SNORM = 84,
	TIF_DXGI_FORMAT_B5G6R5_UNORM = 85,
	TIF_DXGI_FORMAT_B5G5R5A1_UNORM = 86,
	TIF_DXGI_FORMAT_B8G8R8A8_UNORM = 87,
	TIF_DXGI_FORMAT_B8G8R8X8_UNORM = 88,
	TIF_DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM = 89,
	TIF_DXGI_FORMAT_B8G8R8A8_TYPELESS = 90,
	TIF_DXGI_FORMAT_B8G8R8A8_UNORM_SRGB = 91,
	TIF_DXGI_FORMAT_B8G8R8X8_TYPELESS = 92,
	TIF_DXGI_FORMAT_B8G8R8X8_UNORM_SRGB = 93,
	TIF_DXGI_FORMAT_BC6H_TYPELESS = 94,
	TIF_DXGI_FORMAT_BC6H_UF16 = 95,
	TIF_DXGI_FORMAT_BC6H_SF16 = 96,
	TIF_DXGI_FORMAT_BC7_TYPELESS = 97,
	TIF_DXGI_FORMAT_BC7_UNORM = 98,
	TIF_DXGI_FORMAT_BC7_UNORM_SRGB = 99,
	TIF_DXGI_FORMAT_AYUV = 100,
	TIF_DXGI_FORMAT_Y410 = 101,
	TIF_DXGI_FORMAT_Y416 = 102,
	TIF_DXGI_FORMAT_NV12 = 103,
	TIF_DXGI_FORMAT_P010 = 104,
	TIF_DXGI_FORMAT_P016 = 105,
	TIF_DXGI_FORMAT_420_OPAQUE = 106,
	TIF_DXGI_FORMAT_YUY2 = 107,
	TIF_DXGI_FORMAT_Y210 = 108,
	TIF_DXGI_FORMAT_Y216 = 109,
	TIF_DXGI_FORMAT_NV11 = 110,
	TIF_DXGI_FORMAT_AI44 = 111,
	TIF_DXGI_FORMAT_IA44 = 112,
	TIF_DXGI_FORMAT_P8 = 113,
	TIF_DXGI_FORMAT_A8P8 = 114,
	TIF_DXGI_FORMAT_B4G4R4A4_UNORM = 115,

	// xbox 360 formats
	TIF_DXGI_FORMAT_R10G10B10_7E3_A2_FLOAT = 116,
	TIF_DXGI_FORMAT_R10G10B10_6E4_A2_FLOAT = 117,
	TIF_DXGI_FORMAT_D16_UNORM_S8_UINT = 118,
	TIF_DXGI_FORMAT_R16_UNORM_X8_TYPELESS = 119,
	TIF_DXGI_FORMAT_X16_TYPELESS_G8_UINT = 120,

	TIF_DXGI_FORMAT_P208 = 130,
	TIF_DXGI_FORMAT_V208 = 131,
	TIF_DXGI_FORMAT_V408 = 132,

	// XBox One formats
	TIF_DXGI_FORMAT_R10G10B10_SNORM_A2_UNORM = 189,
	TIF_DXGI_FORMAT_R4G4_UNORM = 190,

} TinyImageFormat_DXGI_FORMAT;
#endif

inline TinyImageFormat TinyImageFormat_FromDXGI_FORMAT(TinyImageFormat_DXGI_FORMAT fmt) {
	switch (fmt) {
	case TIF_DXGI_FORMAT_UNKNOWN: return TinyImageFormat_UNDEFINED;
	case TIF_DXGI_FORMAT_R32G32B32A32_FLOAT: return TinyImageFormat_R32G32B32A32_SFLOAT;
	case TIF_DXGI_FORMAT_R32G32B32A32_UINT: return TinyImageFormat_R32G32B32A32_UINT;
	case TIF_DXGI_FORMAT_R32G32B32A32_SINT: return TinyImageFormat_R32G32B32A32_SINT;
	case TIF_DXGI_FORMAT_R32G32B32_FLOAT: return TinyImageFormat_R32G32B32_SFLOAT;
	case TIF_DXGI_FORMAT_R32G32B32_UINT: return TinyImageFormat_R32G32B32_UINT;
	case TIF_DXGI_FORMAT_R32G32B32_SINT: return TinyImageFormat_R32G32B32_SINT;
	case TIF_DXGI_FORMAT_R16G16B16A16_FLOAT: return TinyImageFormat_R16G16B16A16_SFLOAT;
	case TIF_DXGI_FORMAT_R16G16B16A16_UNORM: return TinyImageFormat_R16G16B16A16_UNORM;
	case TIF_DXGI_FORMAT_R16G16B16A16_UINT: return TinyImageFormat_R16G16B16A16_UINT;
	case TIF_DXGI_FORMAT_R16G16B16A16_SNORM: return TinyImageFormat_R16G16B16A16_SNORM;
	case TIF_DXGI_FORMAT_R16G16B16A16_SINT: return TinyImageFormat_R16G16B16A16_SINT;
	case TIF_DXGI_FORMAT_R32G32_FLOAT: return TinyImageFormat_R32G32_SFLOAT;
	case TIF_DXGI_FORMAT_R32G32_UINT: return TinyImageFormat_R32G32_UINT;
	case TIF_DXGI_FORMAT_R32G32_SINT: return TinyImageFormat_R32G32_SINT;
	case TIF_DXGI_FORMAT_D32_FLOAT_S8X24_UINT: return TinyImageFormat_D32_SFLOAT_S8_UINT;
	case TIF_DXGI_FORMAT_R10G10B10A2_UNORM: return TinyImageFormat_A2B10G10R10_UNORM;
	case TIF_DXGI_FORMAT_R10G10B10A2_UINT: return TinyImageFormat_A2B10G10R10_UINT;
	case TIF_DXGI_FORMAT_R11G11B10_FLOAT: return TinyImageFormat_B10G11R11_UFLOAT;
	case TIF_DXGI_FORMAT_R8G8B8A8_UNORM: return TinyImageFormat_R8G8B8A8_UNORM;
	case TIF_DXGI_FORMAT_R16G16_FLOAT: return TinyImageFormat_R16G16_SFLOAT;
	case TIF_DXGI_FORMAT_R16G16_UNORM: return TinyImageFormat_R16G16_UNORM;
	case TIF_DXGI_FORMAT_R16G16_UINT: return TinyImageFormat_R16G16_UINT;
	case TIF_DXGI_FORMAT_R16G16_SNORM: return TinyImageFormat_R16G16_SNORM;
	case TIF_DXGI_FORMAT_R16G16_SINT: return TinyImageFormat_R16G16_SINT;
	case TIF_DXGI_FORMAT_D32_FLOAT: return TinyImageFormat_D32_SFLOAT;
	case TIF_DXGI_FORMAT_R32_FLOAT: return TinyImageFormat_R32_SFLOAT;
	case TIF_DXGI_FORMAT_R32_UINT: return TinyImageFormat_R32_UINT;
	case TIF_DXGI_FORMAT_R32_SINT: return TinyImageFormat_R32_SINT;
	case TIF_DXGI_FORMAT_D24_UNORM_S8_UINT: return TinyImageFormat_D24_UNORM_S8_UINT;
	case TIF_DXGI_FORMAT_X24_TYPELESS_G8_UINT: return TinyImageFormat_D24_UNORM_S8_UINT;
	case TIF_DXGI_FORMAT_R8G8_UNORM: return TinyImageFormat_R8G8_UNORM;
	case TIF_DXGI_FORMAT_R8G8_UINT: return TinyImageFormat_R8G8_UINT;
	case TIF_DXGI_FORMAT_R8G8_SNORM: return TinyImageFormat_R8G8_SNORM;
	case TIF_DXGI_FORMAT_R8G8_SINT: return TinyImageFormat_R8G8_SINT;
	case TIF_DXGI_FORMAT_R16_FLOAT: return TinyImageFormat_R16_SFLOAT;
	case TIF_DXGI_FORMAT_D16_UNORM: return TinyImageFormat_D16_UNORM;
	case TIF_DXGI_FORMAT_R16_UNORM: return TinyImageFormat_R16_UNORM;
	case TIF_DXGI_FORMAT_R16_UINT: return TinyImageFormat_R16_UINT;
	case TIF_DXGI_FORMAT_R16_SNORM: return TinyImageFormat_R16_SNORM;
	case TIF_DXGI_FORMAT_R16_SINT: return TinyImageFormat_R16_SINT;
	case TIF_DXGI_FORMAT_R8_UNORM: return TinyImageFormat_R8_UNORM;
	case TIF_DXGI_FORMAT_R8_UINT: return TinyImageFormat_R8_UINT;
	case TIF_DXGI_FORMAT_R8_SNORM: return TinyImageFormat_R8_SNORM;
	case TIF_DXGI_FORMAT_R8_SINT: return TinyImageFormat_R8_SINT;
	case TIF_DXGI_FORMAT_A8_UNORM: return TinyImageFormat_R8_UNORM;
	case TIF_DXGI_FORMAT_R9G9B9E5_SHAREDEXP: return TinyImageFormat_E5B9G9R9_UFLOAT;
	case TIF_DXGI_FORMAT_BC1_UNORM: return TinyImageFormat_DXBC1_RGBA_UNORM;
	case TIF_DXGI_FORMAT_BC1_UNORM_SRGB: return TinyImageFormat_DXBC1_RGBA_SRGB;
	case TIF_DXGI_FORMAT_BC2_UNORM: return TinyImageFormat_DXBC2_UNORM;
	case TIF_DXGI_FORMAT_BC2_UNORM_SRGB: return TinyImageFormat_DXBC2_SRGB;
	case TIF_DXGI_FORMAT_BC3_UNORM: return TinyImageFormat_DXBC3_UNORM;
	case TIF_DXGI_FORMAT_BC3_UNORM_SRGB: return TinyImageFormat_DXBC3_SRGB;
	case TIF_DXGI_FORMAT_BC4_UNORM: return TinyImageFormat_DXBC4_UNORM;
	case TIF_DXGI_FORMAT_BC4_SNORM: return TinyImageFormat_DXBC4_SNORM;
	case TIF_DXGI_FORMAT_BC5_UNORM: return TinyImageFormat_DXBC5_UNORM;
	case TIF_DXGI_FORMAT_BC5_SNORM: return TinyImageFormat_DXBC5_SNORM;
	case TIF_DXGI_FORMAT_B5G6R5_UNORM: return TinyImageFormat_R5G6B5_UNORM;
	case TIF_DXGI_FORMAT_B5G5R5A1_UNORM: return TinyImageFormat_R5G5B5A1_UNORM;
	case TIF_DXGI_FORMAT_B8G8R8A8_UNORM: return TinyImageFormat_B8G8R8A8_UNORM;
	case TIF_DXGI_FORMAT_B8G8R8X8_UNORM: return TinyImageFormat_B8G8R8A8_UNORM;
	case TIF_DXGI_FORMAT_B8G8R8A8_UNORM_SRGB: return TinyImageFormat_B8G8R8A8_SRGB;
	case TIF_DXGI_FORMAT_B8G8R8X8_UNORM_SRGB: return TinyImageFormat_B8G8R8A8_SRGB;
	case TIF_DXGI_FORMAT_BC6H_UF16: return TinyImageFormat_DXBC6H_UFLOAT;
	case TIF_DXGI_FORMAT_BC6H_SF16: return TinyImageFormat_DXBC6H_SFLOAT;
	case TIF_DXGI_FORMAT_BC7_UNORM: return TinyImageFormat_DXBC7_UNORM;
	case TIF_DXGI_FORMAT_BC7_UNORM_SRGB: return TinyImageFormat_DXBC7_SRGB;
	case TIF_DXGI_FORMAT_B4G4R4A4_UNORM: return TinyImageFormat_B4G4R4A4_UNORM;
	case TIF_DXGI_FORMAT_R8G8B8A8_UNORM_SRGB: return TinyImageFormat_R8G8B8A8_SRGB;
	case TIF_DXGI_FORMAT_R8G8B8A8_UINT: return TinyImageFormat_R8G8B8A8_UINT;
	case TIF_DXGI_FORMAT_R8G8B8A8_SNORM: return TinyImageFormat_R8G8B8A8_SNORM;
	case TIF_DXGI_FORMAT_R8G8B8A8_SINT: return TinyImageFormat_R8G8B8A8_SINT;
	case TIF_DXGI_FORMAT_R4G4_UNORM: return TinyImageFormat_R4G4_UNORM;

	case TIF_DXGI_FORMAT_R32G32B32A32_TYPELESS:
	case TIF_DXGI_FORMAT_R32G32B32_TYPELESS:
	case TIF_DXGI_FORMAT_R16G16B16A16_TYPELESS:
	case TIF_DXGI_FORMAT_R32G32_TYPELESS:
	case TIF_DXGI_FORMAT_R32G8X24_TYPELESS:
	case TIF_DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS:
	case TIF_DXGI_FORMAT_X32_TYPELESS_G8X24_UINT:
	case TIF_DXGI_FORMAT_R10G10B10A2_TYPELESS:
	case TIF_DXGI_FORMAT_R8G8B8A8_TYPELESS:
	case TIF_DXGI_FORMAT_R16G16_TYPELESS:
	case TIF_DXGI_FORMAT_R32_TYPELESS:
	case TIF_DXGI_FORMAT_R24G8_TYPELESS:
	case TIF_DXGI_FORMAT_R24_UNORM_X8_TYPELESS:
	case TIF_DXGI_FORMAT_R8G8_TYPELESS:
	case TIF_DXGI_FORMAT_R16_TYPELESS:
	case TIF_DXGI_FORMAT_R8_TYPELESS:
	case TIF_DXGI_FORMAT_R1_UNORM:
	case TIF_DXGI_FORMAT_BC1_TYPELESS:
	case TIF_DXGI_FORMAT_BC2_TYPELESS:
	case TIF_DXGI_FORMAT_BC3_TYPELESS:
	case TIF_DXGI_FORMAT_BC4_TYPELESS:
	case TIF_DXGI_FORMAT_BC5_TYPELESS:
	case TIF_DXGI_FORMAT_B8G8R8A8_TYPELESS:
	case TIF_DXGI_FORMAT_B8G8R8X8_TYPELESS:
	case TIF_DXGI_FORMAT_BC6H_TYPELESS:
	case TIF_DXGI_FORMAT_BC7_TYPELESS:
	case TIF_DXGI_FORMAT_AYUV:
	case TIF_DXGI_FORMAT_Y410:
	case TIF_DXGI_FORMAT_Y416:
	case TIF_DXGI_FORMAT_NV12:
	case TIF_DXGI_FORMAT_P010:
	case TIF_DXGI_FORMAT_P016:
	case TIF_DXGI_FORMAT_420_OPAQUE:
	case TIF_DXGI_FORMAT_YUY2:
	case TIF_DXGI_FORMAT_Y210:
	case TIF_DXGI_FORMAT_Y216:
	case TIF_DXGI_FORMAT_NV11:
	case TIF_DXGI_FORMAT_AI44:
	case TIF_DXGI_FORMAT_IA44:
	case TIF_DXGI_FORMAT_P8:
	case TIF_DXGI_FORMAT_A8P8:
	case TIF_DXGI_FORMAT_P208:
	case TIF_DXGI_FORMAT_V208:
	case TIF_DXGI_FORMAT_V408:
	case TIF_DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM:
	case TIF_DXGI_FORMAT_R8G8_B8G8_UNORM:
	case TIF_DXGI_FORMAT_G8R8_G8B8_UNORM:
	case TIF_DXGI_FORMAT_R10G10B10_7E3_A2_FLOAT:
	case TIF_DXGI_FORMAT_R10G10B10_6E4_A2_FLOAT:
	case TIF_DXGI_FORMAT_D16_UNORM_S8_UINT:
	case TIF_DXGI_FORMAT_R16_UNORM_X8_TYPELESS:
	case TIF_DXGI_FORMAT_X16_TYPELESS_G8_UINT:
	case TIF_DXGI_FORMAT_R10G10B10_SNORM_A2_UNORM:
		return TinyImageFormat_UNDEFINED;
	}
	return TinyImageFormat_UNDEFINED;
}

inline TinyImageFormat_DXGI_FORMAT TinyImageFormat_ToDXGI_FORMAT(TinyImageFormat fmt) {
	switch (fmt) {
	case TinyImageFormat_UNDEFINED: return TIF_DXGI_FORMAT_UNKNOWN;
	case TinyImageFormat_R5G6B5_UNORM: return TIF_DXGI_FORMAT_B5G6R5_UNORM;
	case TinyImageFormat_B5G6R5_UNORM: return TIF_DXGI_FORMAT_B5G6R5_UNORM;
	case TinyImageFormat_A1R5G5B5_UNORM: return TIF_DXGI_FORMAT_B5G5R5A1_UNORM;
	case TinyImageFormat_R8_UNORM: return TIF_DXGI_FORMAT_R8_UNORM;
	case TinyImageFormat_R8_SNORM: return TIF_DXGI_FORMAT_R8_SNORM;
	case TinyImageFormat_R8_UINT: return TIF_DXGI_FORMAT_R8_UINT;
	case TinyImageFormat_R8_SINT: return TIF_DXGI_FORMAT_R8_SINT;
	case TinyImageFormat_R8G8_UNORM: return TIF_DXGI_FORMAT_R8G8_UNORM;
	case TinyImageFormat_R8G8_SNORM: return TIF_DXGI_FORMAT_R8G8_SNORM;
	case TinyImageFormat_R8G8_UINT: return TIF_DXGI_FORMAT_R8G8_UINT;
	case TinyImageFormat_R8G8_SINT: return TIF_DXGI_FORMAT_R8G8_SINT;
	case TinyImageFormat_R8G8B8A8_UNORM: return TIF_DXGI_FORMAT_R8G8B8A8_UNORM;
	case TinyImageFormat_R8G8B8A8_SNORM: return TIF_DXGI_FORMAT_R8G8B8A8_SNORM;
	case TinyImageFormat_R8G8B8A8_UINT: return TIF_DXGI_FORMAT_R8G8B8A8_UINT;
	case TinyImageFormat_R8G8B8A8_SINT: return TIF_DXGI_FORMAT_R8G8B8A8_SINT;
	case TinyImageFormat_R8G8B8A8_SRGB: return TIF_DXGI_FORMAT_R8G8B8A8_UNORM_SRGB;
	case TinyImageFormat_B8G8R8A8_UNORM: return TIF_DXGI_FORMAT_B8G8R8A8_UNORM;
	case TinyImageFormat_A2B10G10R10_UNORM: return TIF_DXGI_FORMAT_R10G10B10A2_UNORM;
	case TinyImageFormat_A2B10G10R10_UINT: return TIF_DXGI_FORMAT_R10G10B10A2_UINT;
	case TinyImageFormat_R16_UNORM: return TIF_DXGI_FORMAT_R16_UNORM;
	case TinyImageFormat_R16_SNORM: return TIF_DXGI_FORMAT_R16_SNORM;
	case TinyImageFormat_R16_UINT: return TIF_DXGI_FORMAT_R16_UINT;
	case TinyImageFormat_R16_SINT: return TIF_DXGI_FORMAT_R16_SINT;
	case TinyImageFormat_R16_SFLOAT: return TIF_DXGI_FORMAT_R16_FLOAT;
	case TinyImageFormat_R16G16_UNORM: return TIF_DXGI_FORMAT_R16G16_UNORM;
	case TinyImageFormat_R16G16_SNORM: return TIF_DXGI_FORMAT_R16G16_SNORM;
	case TinyImageFormat_R16G16_UINT: return TIF_DXGI_FORMAT_R16G16_UINT;
	case TinyImageFormat_R16G16_SINT: return TIF_DXGI_FORMAT_R16G16_SINT;
	case TinyImageFormat_R16G16_SFLOAT: return TIF_DXGI_FORMAT_R16G16_FLOAT;
	case TinyImageFormat_R16G16B16A16_UNORM: return TIF_DXGI_FORMAT_R16G16B16A16_UNORM;
	case TinyImageFormat_R16G16B16A16_SNORM: return TIF_DXGI_FORMAT_R16G16B16A16_SNORM;
	case TinyImageFormat_R16G16B16A16_UINT: return TIF_DXGI_FORMAT_R16G16B16A16_UINT;
	case TinyImageFormat_R16G16B16A16_SINT: return TIF_DXGI_FORMAT_R16G16B16A16_SINT;
	case TinyImageFormat_R16G16B16A16_SFLOAT: return TIF_DXGI_FORMAT_R16G16B16A16_FLOAT;
	case TinyImageFormat_R32_UINT: return TIF_DXGI_FORMAT_R32_UINT;
	case TinyImageFormat_R32_SINT: return TIF_DXGI_FORMAT_R32_SINT;
	case TinyImageFormat_R32_SFLOAT: return TIF_DXGI_FORMAT_R32_FLOAT;
	case TinyImageFormat_R32G32_UINT: return TIF_DXGI_FORMAT_R32G32_UINT;
	case TinyImageFormat_R32G32_SINT: return TIF_DXGI_FORMAT_R32G32_SINT;
	case TinyImageFormat_R32G32_SFLOAT: return TIF_DXGI_FORMAT_R32G32_FLOAT;
	case TinyImageFormat_R32G32B32_UINT: return TIF_DXGI_FORMAT_R32G32B32_UINT;
	case TinyImageFormat_R32G32B32_SINT: return TIF_DXGI_FORMAT_R32G32B32_SINT;
	case TinyImageFormat_R32G32B32_SFLOAT: return TIF_DXGI_FORMAT_R32G32B32_FLOAT;
	case TinyImageFormat_R32G32B32A32_UINT: return TIF_DXGI_FORMAT_R32G32B32A32_UINT;
	case TinyImageFormat_R32G32B32A32_SINT: return TIF_DXGI_FORMAT_R32G32B32A32_SINT;
	case TinyImageFormat_R32G32B32A32_SFLOAT: return TIF_DXGI_FORMAT_R32G32B32A32_FLOAT;
	case TinyImageFormat_B10G11R11_UFLOAT: return TIF_DXGI_FORMAT_R11G11B10_FLOAT;
	case TinyImageFormat_E5B9G9R9_UFLOAT: return TIF_DXGI_FORMAT_R9G9B9E5_SHAREDEXP;
	case TinyImageFormat_D16_UNORM: return TIF_DXGI_FORMAT_D16_UNORM;
	case TinyImageFormat_X8_D24_UNORM: return TIF_DXGI_FORMAT_D24_UNORM_S8_UINT;
	case TinyImageFormat_D32_SFLOAT: return TIF_DXGI_FORMAT_D32_FLOAT;
	case TinyImageFormat_D24_UNORM_S8_UINT: return TIF_DXGI_FORMAT_D24_UNORM_S8_UINT;
	case TinyImageFormat_D32_SFLOAT_S8_UINT: return TIF_DXGI_FORMAT_D32_FLOAT_S8X24_UINT;
	case TinyImageFormat_DXBC1_RGB_UNORM: return TIF_DXGI_FORMAT_BC1_UNORM;
	case TinyImageFormat_DXBC1_RGB_SRGB: return TIF_DXGI_FORMAT_BC1_UNORM_SRGB;
	case TinyImageFormat_DXBC1_RGBA_UNORM: return TIF_DXGI_FORMAT_BC1_UNORM;
	case TinyImageFormat_DXBC1_RGBA_SRGB: return TIF_DXGI_FORMAT_BC1_UNORM_SRGB;
	case TinyImageFormat_DXBC2_UNORM: return TIF_DXGI_FORMAT_BC2_UNORM;
	case TinyImageFormat_DXBC2_SRGB: return TIF_DXGI_FORMAT_BC2_UNORM_SRGB;
	case TinyImageFormat_DXBC3_UNORM: return TIF_DXGI_FORMAT_BC3_UNORM;
	case TinyImageFormat_DXBC3_SRGB: return TIF_DXGI_FORMAT_BC3_UNORM_SRGB;
	case TinyImageFormat_DXBC4_UNORM: return TIF_DXGI_FORMAT_BC4_UNORM;
	case TinyImageFormat_DXBC4_SNORM: return TIF_DXGI_FORMAT_BC4_SNORM;
	case TinyImageFormat_DXBC5_UNORM: return TIF_DXGI_FORMAT_BC5_UNORM;
	case TinyImageFormat_DXBC5_SNORM: return TIF_DXGI_FORMAT_BC5_SNORM;
	case TinyImageFormat_DXBC6H_UFLOAT: return TIF_DXGI_FORMAT_BC6H_UF16;
	case TinyImageFormat_DXBC6H_SFLOAT: return TIF_DXGI_FORMAT_BC6H_SF16;
	case TinyImageFormat_DXBC7_UNORM: return TIF_DXGI_FORMAT_BC7_UNORM;
	case TinyImageFormat_DXBC7_SRGB: return TIF_DXGI_FORMAT_BC7_UNORM_SRGB;
	case TinyImageFormat_A4R4G4B4_UNORM: return TIF_DXGI_FORMAT_B4G4R4A4_UNORM;
	case TinyImageFormat_R4G4_UNORM: return TIF_DXGI_FORMAT_R4G4_UNORM;
	default: return TIF_DXGI_FORMAT_UNKNOWN;

	}
	return TIF_DXGI_FORMAT_UNKNOWN;
}

inline TinyImageFormat_DXGI_FORMAT TinyImageFormat_DXGI_FORMATToTypeless(TinyImageFormat_DXGI_FORMAT fmt) {
	switch (fmt) {
	case TIF_DXGI_FORMAT_R32G32B32A32_FLOAT:
	case TIF_DXGI_FORMAT_R32G32B32A32_UINT:
	case TIF_DXGI_FORMAT_R32G32B32A32_SINT: return TIF_DXGI_FORMAT_R32G32B32A32_TYPELESS;
	case TIF_DXGI_FORMAT_R32G32B32_FLOAT:
	case TIF_DXGI_FORMAT_R32G32B32_UINT:
	case TIF_DXGI_FORMAT_R32G32B32_SINT: return TIF_DXGI_FORMAT_R32G32B32_TYPELESS;
	case TIF_DXGI_FORMAT_R16G16B16A16_FLOAT:
	case TIF_DXGI_FORMAT_R16G16B16A16_UNORM:
	case TIF_DXGI_FORMAT_R16G16B16A16_UINT:
	case TIF_DXGI_FORMAT_R16G16B16A16_SNORM:
	case TIF_DXGI_FORMAT_R16G16B16A16_SINT: return TIF_DXGI_FORMAT_R16G16B16A16_TYPELESS;
	case TIF_DXGI_FORMAT_R32G32_FLOAT:
	case TIF_DXGI_FORMAT_R32G32_UINT:
	case TIF_DXGI_FORMAT_R32G32_SINT: return TIF_DXGI_FORMAT_R32G32_TYPELESS;
	case TIF_DXGI_FORMAT_R10G10B10A2_UNORM:
	case TIF_DXGI_FORMAT_R10G10B10A2_UINT: return TIF_DXGI_FORMAT_R10G10B10A2_TYPELESS;
	case TIF_DXGI_FORMAT_R8G8B8A8_UNORM:
	case TIF_DXGI_FORMAT_R8G8B8A8_UNORM_SRGB:
	case TIF_DXGI_FORMAT_R8G8B8A8_UINT:
	case TIF_DXGI_FORMAT_R8G8B8A8_SNORM:
	case TIF_DXGI_FORMAT_R8G8B8A8_SINT: return TIF_DXGI_FORMAT_R8G8B8A8_TYPELESS;
	case TIF_DXGI_FORMAT_R16G16_FLOAT:
	case TIF_DXGI_FORMAT_R16G16_UNORM:
	case TIF_DXGI_FORMAT_R16G16_UINT:
	case TIF_DXGI_FORMAT_R16G16_SNORM:
	case TIF_DXGI_FORMAT_R16G16_SINT: return TIF_DXGI_FORMAT_R16G16_TYPELESS;

	case TIF_DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM:
	case TIF_DXGI_FORMAT_R9G9B9E5_SHAREDEXP:
	case TIF_DXGI_FORMAT_R11G11B10_FLOAT: // closest typeless is raw 32 bits
	case TIF_DXGI_FORMAT_D32_FLOAT:
	case TIF_DXGI_FORMAT_R32_FLOAT:
	case TIF_DXGI_FORMAT_R32_UINT:
	case TIF_DXGI_FORMAT_R32_SINT: return TIF_DXGI_FORMAT_R32_TYPELESS;
	case TIF_DXGI_FORMAT_R8G8_UNORM:
	case TIF_DXGI_FORMAT_R8G8_UINT:
	case TIF_DXGI_FORMAT_R8G8_SNORM:
	case TIF_DXGI_FORMAT_R8G8_SINT: return TIF_DXGI_FORMAT_R8G8_TYPELESS;
	case TIF_DXGI_FORMAT_B4G4R4A4_UNORM: // just treats a 16 raw bits
	case TIF_DXGI_FORMAT_D16_UNORM:
	case TIF_DXGI_FORMAT_R16_FLOAT:
	case TIF_DXGI_FORMAT_R16_UNORM:
	case TIF_DXGI_FORMAT_R16_UINT:
	case TIF_DXGI_FORMAT_R16_SNORM:
	case TIF_DXGI_FORMAT_R16_SINT: return TIF_DXGI_FORMAT_R16_TYPELESS;
	case TIF_DXGI_FORMAT_A8_UNORM:
	case TIF_DXGI_FORMAT_R8_UNORM:
	case TIF_DXGI_FORMAT_R8_UINT:
	case TIF_DXGI_FORMAT_R8_SNORM:
	case TIF_DXGI_FORMAT_R4G4_UNORM:
	case TIF_DXGI_FORMAT_R8_SINT: return TIF_DXGI_FORMAT_R8_TYPELESS;
	case TIF_DXGI_FORMAT_BC1_UNORM:
	case TIF_DXGI_FORMAT_BC1_UNORM_SRGB: return TIF_DXGI_FORMAT_BC1_TYPELESS;
	case TIF_DXGI_FORMAT_BC2_UNORM:
	case TIF_DXGI_FORMAT_BC2_UNORM_SRGB: return TIF_DXGI_FORMAT_BC2_TYPELESS;
	case TIF_DXGI_FORMAT_BC3_UNORM:
	case TIF_DXGI_FORMAT_BC3_UNORM_SRGB: return TIF_DXGI_FORMAT_BC3_TYPELESS;
	case TIF_DXGI_FORMAT_BC4_UNORM:
	case TIF_DXGI_FORMAT_BC4_SNORM: return TIF_DXGI_FORMAT_BC4_TYPELESS;
	case TIF_DXGI_FORMAT_BC5_UNORM:
	case TIF_DXGI_FORMAT_BC5_SNORM: return TIF_DXGI_FORMAT_BC5_TYPELESS;
	case TIF_DXGI_FORMAT_B5G6R5_UNORM:
	case TIF_DXGI_FORMAT_B5G5R5A1_UNORM: return TIF_DXGI_FORMAT_R16_TYPELESS;
	case TIF_DXGI_FORMAT_B8G8R8A8_UNORM:
	case TIF_DXGI_FORMAT_B8G8R8X8_UNORM:
	case TIF_DXGI_FORMAT_B8G8R8A8_UNORM_SRGB:
	case TIF_DXGI_FORMAT_B8G8R8X8_UNORM_SRGB: return TIF_DXGI_FORMAT_B8G8R8A8_UNORM;
	case TIF_DXGI_FORMAT_BC6H_UF16:
	case TIF_DXGI_FORMAT_BC6H_SF16: return TIF_DXGI_FORMAT_BC6H_TYPELESS;
	case TIF_DXGI_FORMAT_BC7_UNORM:
	case TIF_DXGI_FORMAT_BC7_UNORM_SRGB: return TIF_DXGI_FORMAT_BC7_TYPELESS;

	case TIF_DXGI_FORMAT_X32_TYPELESS_G8X24_UINT:
	case TIF_DXGI_FORMAT_D32_FLOAT_S8X24_UINT: return TIF_DXGI_FORMAT_R32G32_TYPELESS;
	case TIF_DXGI_FORMAT_X24_TYPELESS_G8_UINT: return TIF_DXGI_FORMAT_R24G8_TYPELESS;
	case TIF_DXGI_FORMAT_D24_UNORM_S8_UINT: return TIF_DXGI_FORMAT_R24G8_TYPELESS;

		// typeless just return the input format
	case TIF_DXGI_FORMAT_R32G32B32A32_TYPELESS:
	case TIF_DXGI_FORMAT_R32G32B32_TYPELESS:
	case TIF_DXGI_FORMAT_R16G16B16A16_TYPELESS:
	case TIF_DXGI_FORMAT_R32G32_TYPELESS:
	case TIF_DXGI_FORMAT_R32G8X24_TYPELESS:
	case TIF_DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS:
	case TIF_DXGI_FORMAT_R10G10B10A2_TYPELESS:
	case TIF_DXGI_FORMAT_R8G8B8A8_TYPELESS:
	case TIF_DXGI_FORMAT_R16G16_TYPELESS:
	case TIF_DXGI_FORMAT_R32_TYPELESS:
	case TIF_DXGI_FORMAT_R24G8_TYPELESS:
	case TIF_DXGI_FORMAT_R24_UNORM_X8_TYPELESS:
	case TIF_DXGI_FORMAT_R8G8_TYPELESS:
	case TIF_DXGI_FORMAT_R16_TYPELESS:
	case TIF_DXGI_FORMAT_R8_TYPELESS:
	case TIF_DXGI_FORMAT_BC1_TYPELESS:
	case TIF_DXGI_FORMAT_BC2_TYPELESS:
	case TIF_DXGI_FORMAT_BC3_TYPELESS:
	case TIF_DXGI_FORMAT_BC4_TYPELESS:
	case TIF_DXGI_FORMAT_BC5_TYPELESS:
	case TIF_DXGI_FORMAT_B8G8R8A8_TYPELESS:
	case TIF_DXGI_FORMAT_B8G8R8X8_TYPELESS:
	case TIF_DXGI_FORMAT_BC6H_TYPELESS:
	case TIF_DXGI_FORMAT_BC7_TYPELESS: return fmt;

	case TIF_DXGI_FORMAT_R1_UNORM:
	case TIF_DXGI_FORMAT_R8G8_B8G8_UNORM:
	case TIF_DXGI_FORMAT_G8R8_G8B8_UNORM:
	case TIF_DXGI_FORMAT_AYUV:
	case TIF_DXGI_FORMAT_Y410:
	case TIF_DXGI_FORMAT_Y416:
	case TIF_DXGI_FORMAT_NV12:
	case TIF_DXGI_FORMAT_P010:
	case TIF_DXGI_FORMAT_P016:
	case TIF_DXGI_FORMAT_420_OPAQUE:
	case TIF_DXGI_FORMAT_YUY2:
	case TIF_DXGI_FORMAT_Y210:
	case TIF_DXGI_FORMAT_Y216:
	case TIF_DXGI_FORMAT_NV11:
	case TIF_DXGI_FORMAT_AI44:
	case TIF_DXGI_FORMAT_IA44:
	case TIF_DXGI_FORMAT_P8:
	case TIF_DXGI_FORMAT_A8P8:
	case TIF_DXGI_FORMAT_P208:
	case TIF_DXGI_FORMAT_V208:
	case TIF_DXGI_FORMAT_V408:
	case TIF_DXGI_FORMAT_R10G10B10_7E3_A2_FLOAT:
	case TIF_DXGI_FORMAT_R10G10B10_6E4_A2_FLOAT:
	case TIF_DXGI_FORMAT_D16_UNORM_S8_UINT:
	case TIF_DXGI_FORMAT_R16_UNORM_X8_TYPELESS:
	case TIF_DXGI_FORMAT_X16_TYPELESS_G8_UINT:
	case TIF_DXGI_FORMAT_R10G10B10_SNORM_A2_UNORM:
	case TIF_DXGI_FORMAT_UNKNOWN: return TIF_DXGI_FORMAT_UNKNOWN;
	}
			TinyImageFormat_ASSERT(false);
	return TIF_DXGI_FORMAT_UNKNOWN;
}

